### ISSUE TITLE
Should remove requires of pprint in setup.py

### ISSUE THREAD

**Issue by aeharvlee** [dkfinance/xbrl-parser#6]
pprint is a standard package of Pyhton3.
so, install guide in README.md does not work.
```
git clone https://github.com/dkfinance/xbrl-parser.git

cd xbrl-parser

pip install -e .
```

produces errors
```
ERROR: Could not find a version that satisfies the requirement pprint (from xbrl-report-parser==0.0.4) (from versions: none)
ERROR: No matching distribution found for pprint (from xbrl-report-parser==0.0.4)
```

I solved this issue with removing line 28 "install_requires=["pprint"]," in `setup.py`.

If it looks good, I want to make a pull request.

**Comment by nymann** [comment]
Hi @aeharvlee 

Thanks for your message.
This project has been dormant for some time, but I would be happy to help here.

I think I added the feature to make the print output neater in `xbrl_parser/console_scripts/__init__.py`. But let's just remove it for now.

**Comment by aeharvlee** [comment]
@nymann Thanks for your comment and great project btw.
I created PR, so I would be happy if you check it 😄
